#+title: Projets à présenter sur eduvelopers.org

Liste de projets de logiciels libres à présenter sur le site
[[https://www.eduvelopers.org][www.eduvelopers.org]].

** hackinscience.org

Site : [[https://hackinscience.org]]

Soutenir : [[https://www.hackinscience.org/page/sponsor]]

Hackinscience est une plateforme open-source et gratuite développée
par une équipe de passionnés depuis 2013, et permettant d'apprendre à
programmer en Python par le biais d'exercices graduées en difficulté
corrigés automatiquement par le site.

La plateforme propose pour chaque exercice un énoncé et un cadre
permettant de taper et d'évaluer son code directement dans le
navigateur. Avec déjà plus de 60 exercices à son compte, HackInScience
se présente comme une alternative beaucoup plus légère aux piliers du
marché en plaçant l'emphase sur la simplicité.

** Sugarizer

Site : [[https://sugarizer.org]]

Soutenir : [[https://github.com/sponsors/llaske]] ou [[https://liberapay.com/llaske/]]

Sugarizer est une suite pédagogique libre et gratuite. Son interface
reprend les principes ergonomiques de Sugar, la suite logicielle
développée par le projet One Laptop Per Child, et aujourd'hui utilisée
par plus de 2 millions d'enfants dans le monde.

** PDF4Teachers

Site : [[https://pdf4teachers.org]]

Soutenir : [[https://github.com/sponsors/ClementGre]]

PDF4Teachers est un éditeur de fichiers PDF orienté correction de copies.
L'application est basée sur un système de mémorisation des dernières annotations saisies : chaque annotation saisie est ajoutée à une liste dans laquelle on peut récupérer des annotations précédentes. Elle intègre aussi des fonctions de barème, qui permettent de noter les copies plus rapidement (calcul des sommes automatiquement, export dans un tableur...).
PDF4Teachers offre aussi des fonctions de conversions de lots d'images en fichiers PDF, ou encore de rotation et de déplacement de pages d'un document PDF.

** Gcompris

Site : [[https://gcompris.net/index-fr.html]]

Soutenir : [[https://www.patreon.com/join/animtim]]

GCompris est un logiciel éducatif qui propose diverses activités pour
les enfants de 2 à 10 ans.Les activités couvrent de nombreux domaines,
et sont réparties en 8 catégories principales et sous-catégories :
interactions avec l'ordinateur, découverte, sciences, divertissement,
mathématiques, puzzle, lecture, stratégie.

** AbulÉdu

AbulÉdu, c'est plus de quinze ans de création de ressources éducatives
libres francophones (REL), développées à l'origine par des bénévoles,
d'abord au sein d'une communauté informelle et depuis 2010 dans le
cadre de l'association AbulÉdu-fr qui regroupe les membres les plus
actifs.

AbulÉdu, ce sont environ 2.500 serveurs installés, représentant
quelques 50.000 utilisateurs ce qui a permis de mettre en réseau les
ressources informatiques des écoles. Ce sont aussi des logiciels
pédagogiques distribués avec les serveurs AbulÉdu et qui équipent
également d'autres distributions libres pour l'école.

AbulÉdu ce sont également des services numériques libres et éthiques
parmi lesquels data (une banque d'environ 35000 images sous licences
libres et indexées selon la norme scolom-fr) et Edutwit (un réseau
social de production d'écrits courts réservé à la communauté
éducative).

L'ensemble des logiciels de la suite pédagogique et les ressources
éducatives libres ont été conçus pour accompagner les pratiques de
classe.  Des enseignants de maternelle, d'élémentaire et de collège
ont coopéré avec des développeurs amateurs et professionnels, des
graphistes, des élus locaux et des animateurs TICE afin d'élaborer,
tester et valider ces outils et ces ressources.

Liens : 

- [[https://abuledu.org][abuledu.org]]
- [[https://abuledu-fr.org][abuledu-fr.org]]
- [[https://edutwit.fr][edutwit.fr]]
- [[https://data.abuledu.org][data.abuledu.org]]

** Dr.Geo

Site : [[http://www.drgeo.eu]]

Soutenir : [[http://www.drgeo.eu/sponsors/becomesponsor]]

Dr.Geo permet de créer des figures géométriques et de les manipuler
interactivement en respectant leurs contraintes géométriques. Il offre
également la possibilité d’introduire graduellement la programmation.
Il est ainsi utilisable dans des situations d’enseignement allant du
niveau primaire au niveau supérieur.  L’interface utilisateur de
Dr.Geo a été conçue pour allier dans un ensemble harmonieux à la fois
simplicité d’utilisation, ergonomie et fonctionnalités avancées.

** Physic-Shem

Site : [[https://alexfauquette.github.io/physic-shem/]]

Physic-Shem permet de dessiner des circuits électriques. Exportez vos
schémas sous format d'image, de code LaTeX, ou sauvegardez là sur le
serveur pour la partager avec d'autres.  Ne manquez pas non plus le
[[https://alexfauquette.github.io/physic-shem/#/tutorial][tutoriel]]
pour comprendre les bases de la création des circuits électriques en
LaTeX.

** do•doc

Site : [[https://dodoc.fr]]

Soutenir et participer : [[https://forum.latelier-des-chercheurs.fr]]

Conçu pour documenter et créer des récits à partir d'activités pratiques, do•doc (prononcer doudoc) est un outil collaboratif, composite, libre et modulaire. Il permet de capturer des médias (photos, vidéos, sons et stop-motion), de les éditer, de les mettre en page et de les publier au format PDF, web ou vidéo. Son aspect composite permet de le reconfigurer de manière à ce qu'il soit le plus adapté possible à la situation dans laquelle il est déployé. do•doc existe en version application hors-ligne pour Linux, mac et Windows, et en version *webapp* en ligne.

** APSC (ArtsPlastocSequenceConceptor)

Site : [[https://lewebpedagogique.com/apsc]]

Soutenir et participer : [[https://lewebpedagogique.com/apsc/faire-un-don/]]

Il s'agit d'un logiciel (de son nom long ArtsPlastocSequenceConceptor)
pour construire et mettre en forme des séquences pédagogiques en arts
plastiques (dernièrement la version 2.0.0, non documentée pour
l'instant par faute de temps, permet aussi de gérer les disciplines
suivantes : Français, Mathématiques et Technologie).

Dans un fonctionnement courant l'application permet à l’enseignant
d’enregistrer ses préparations sous la forme d’un fichier (avec
extension .artp), et le professeur, peut, dès qu’il le désire, éditer
la la séquence (précédemment préparée), et en produire la fiche du
professeur et dans la foulée la fiche élève, et pour finir la fiche
d’évaluation (avec un tableau comportant la liste des élèves mise en
regard avec les critères d’évaluation).

** MurExpo

Site : [[https://me.murexpo.org]]

Soutenir : [[https://murexpo.org/me/soutenir-faire-un-don/]]

Il s'agit d'un logiciel qui met à disposition des murs d’exposition
sur lesquels on peut accrocher des oeuvres (travaux de plasticiens,
travaux d’élèves, etc.) afin de les mettre en situation comme dans une
salle d’exposition.

MurExpo est très facile d'utilisation et il s'adresse aussi bien aux
élèves qu'aux enseignants.

