#+title: Projets à présenter sur eduvelopers.org

Liste de projets de logiciels libres à présenter sur le site
[[https://www.eduvelopers.org][www.eduvelopers.org]].

** hackinscience.org

Site : [[https://hackinscience.org]]

Soutenir : https://www.hackinscience.org/page/sponsor

Hackinscience est une plateforme open-source et gratuite développée
par une équipe de passionnés depuis 2013, et permettant d'apprendre à
programmer en Python par le biais d'exercices graduées en difficulté
corrigés automatiquement par le site.

La plateforme propose pour chaque exercice un énoncé et un cadre
permettant de taper et d'évaluer son code directement dans le
navigateur. Avec déjà plus de 60 exercices à son compte, HackInScience
se présente comme une alternative beaucoup plus légère aux piliers du
marché en plaçant l'emphase sur la simplicité.

** Sugarizer

Site : [[https://sugarizer.org]]

Sugarizer est une suite pédagogique libre et gratuite. Son interface
reprend les principes ergonomiques de Sugar, la suite logicielle
développée par le projet One Laptop Per Child, et aujourd'hui utilisée
par plus de 2 millions d'enfants dans le monde.

** PDF4Teachers

Site : [[https://pdf4teachers.org]]

Soutenir : https://github.com/sponsors/ClementGre

PDF4Teachers est un éditeur de fichiers PDF orienté correction de copies.
L'application est basée sur un système de mémorisation des dernières annotations saisies : chaque annotation saisie est ajoutée à une liste dans laquelle on peut récupérer des annotations précédentes. Elle intègre aussi des fonctions de barème, qui permettent de noter les copies plus rapidement (calcul des sommes automatiquement, export dans un tableur...).
PDF4Teachers offre aussi des fonctions de conversions de lots d'images en fichiers PDF, ou encore de rotation et de déplacement de pages d'un document PDF.

** Gcompris

Site : https://gcompris.net/index-fr.html

Soutenir : https://www.patreon.com/join/animtim?

GCompris est un logiciel éducatif qui propose diverses activités pour
les enfants de 2 à 10 ans. Il couvre de nombreux domaines, qu'il est
possible d'assimiler à 7 grandes catégories : la découverte de
l'ordinateur, les mathématiques, les sciences, la géographie, les
jeux, la lecture, les autres activités (lecture de l'heure, puzzle,
création d'un dessin animé.)

